WEAT-3 updating ci/cd, adding an environment clean-up

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -46,15 +46,33 @@ jobs:
         id: create-environment  # Step ID to reference the deployment step
         run: |
           branch_name=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')  # Extract the branch name
+          
+          # Check if the branch is "main"
+          if [ "$branch_name" == "main" ]; then
+            env_name="${branch_name}"  # Use "main" as the environment name
+          else
+            # Use grep to extract the Jira ticket ID (assumes it starts with WEAT-)
+            jira_ticket_id=$(echo "$branch_name" | grep -oE 'WEAT-[0-9]+' | head -n 1)
+
+            # Check if the Jira ticket ID was found
+            if [ -z "$jira_ticket_id" ]; then
+              echo "No Jira ticket ID found in branch name. Aborting deployment."
+              exit 1
+            fi
+            
+            env_name="${jira_ticket_id}-eb"  # Create a shorter environment name using the Jira ticket ID
+          fi
+
+          # Initialize and deploy to Elastic Beanstalk using the determined environment name
           eb init efi-smirnov-streamlit-demo-${branch_name} --platform Docker --region eu-west-2 --verbose  # Initialize Elastic Beanstalk application for the current branch
-          eb create ${branch_name}-env --verbose  # Create a new environment for the branch
-          eb deploy ${branch_name}-env  # Deploy the Docker image to the branch-specific Elastic Beanstalk environment
+          eb create ${env_name} --verbose  # Create a new environment for the branch
+          eb deploy ${env_name}  # Deploy the Docker image to the branch-specific Elastic Beanstalk environment
 
       - name: Get Elastic Beanstalk Environment URL
         id: set-url  # Step ID to reference the URL later
         run: |
-          branch_name=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')  # Extract the branch name
-          deployed_url=$(eb status ${branch_name}-env | grep CNAME | awk '{print $2}')  # Get the CNAME (URL) of the newly created environment
+          # Use the previously defined environment name for URL retrieval
+          deployed_url=$(eb status ${env_name} | grep CNAME | awk '{print $2}')  # Get the CNAME (URL) of the newly created environment
           echo "deployed_url=$deployed_url" >> $GITHUB_ENV  # Set the URL as an environment variable for future steps
 
       - name: Set Environment URL
